### ISSUE TITLE
你好，想问下，mineapp的后台可以分享下？qq:1795387338@qq.com

### ISSUE THREAD

**Issue by SuJinTuan** [biaov/MINEAPP#1]

**Comment by biaov** [comment]
> _No description provided._

后台是用react开发的，你还要吗？

**Comment by SuJinTuan** [comment]
你好，如果可以分享的话，没问题。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月16日(星期五) 上午9:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [biaov/MINEAPP] ***@***.*** (#1)





  
No description provided.
  
后台是用react开发的，你还要吗？

**Comment by biaov** [comment]
> 你好，如果可以分享的话，没问题。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年7月16日(星期五) 上午9:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [biaov/MINEAPP] ***@***.*** (#1) No description provided. 后台是用react开发的，你还要吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可以，但是得晚点，这周末才有时间整理，周末发布了通知你

**Comment by SuJinTuan** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月16日(星期五) 上午9:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [biaov/MINEAPP] ***@***.*** (#1)





  
你好，如果可以分享的话，没问题。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年7月16日(星期五) 上午9:03 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [biaov/MINEAPP] @.*** (#1) No description provided. 后台是用react开发的，你还要吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
可以，但是得晚点，这周末才有时间整理，周末发布了通知你

**Comment by biaov** [comment]
> _No description provided._

* MINEAPP的后台管理系统
  * 源码地址：[MINEAPPADMIN](https://gitee.com/MINECASE/mineappadmin)
  * 演示地址：[MINEAPPADMIN](http://mineappadmin.app.biaov.cn/)

**Comment by SuJinTuan** [comment]
好，收到。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月17日(星期六) 晚上6:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [biaov/MINEAPP] ***@***.*** (#1)





  
No description provided.
   
MINEAPP的后台管理系统  
源码地址：MINEAPPADMIN
 
演示地址：MINEAPPADMIN
