### ISSUE TITLE
您好，MINEAPP后台管理系统地址无法访问了，能否重新分享？

### ISSUE THREAD

**Issue by 923325596** [biaov/MINEAPP#4]
我看码云分享的现在无法访问。还有一个问题，就是这个MINEAPP后台管理系统的后台接口是本项目的后台接口吗？

**Comment by biaov** [comment]
> 我看码云分享的现在无法访问。还有一个问题，就是这个MINEAPP后台管理系统的后台接口是本项目的后台接口吗？

码云分享的地址发下？

**Comment by 923325596** [comment]
我看在别的Issue下分享的是这个： https://gitee.com/MINECASE/mineappadmin

**Comment by biaov** [comment]
> 我看在别的Issue下分享的是这个： https://gitee.com/MINECASE/mineappadmin

新地址：https://gitee.com/biaov/mineappadmin
